site_name: Backdraft Docs
site_author: Caleb Grove
site_favicon: favicon.ico
pages:
- Introduction:
    - 'index.md'
    - 1.5 in Freeway 7: '15-in-fw7.md'
- Getting Started:
    - 'installation.md'
    - 'getting-started.md'
- Advanced Topics:
    - 'master-pages.md'
    - 'flexible-graphics.md'
    - 'customizing-modules.md'
    - 'full-width.md'
    - 'hiding-elements.md'
    - 'flexible-iframes.md'
    - 'rollovers.md'
    - 'adjust-css.md'
- Third Party Itegrations:
    - 'exhibeo.md'
    - 'wow-slider.md'
    - 'hype.md'
    - 'webyep.md'
