site_name: Backdraft Docs
site_author: Caleb Grove
site_favicon: favicon.ico
pages:
- Introduction:
    - What's new: 'index.md'
- Getting Started:
    - 'installation.md'
    - Creating your first page: 'getting-started.md'
    - Known Bugs: 'known-bugs.md'
- Advanced Topics:
    - 'master-pages.md'
    - 'flexible-graphics.md'
    - 'customizing-modules.md'
    - Full width elements: 'full-width.md'
    - 'hiding-elements.md'
    - 'flexible-iframes.md'
    - Flexible rollovers: 'rollovers.md'
    - Customizing the CSS: 'adjust-css.md'
- Third Party Itegrations:
    - 'exhibeo.md'
    - 'wow-slider.md'
    - 'hype.md'
    - 'webyep.md'
